services:
  admarketplace:
    image: admarketplace
    ports:
      - "80:8080"
    environment:
      - TelegramBot__Token=${TELEGRAM_TOKEN}
      - TelegramBot__BotApiServer=https://api.telegram.org
      - TelegramBot__WebhookUrl=${WEBHOOK_URL}
      - ConnectionStrings__Main=Host=postgres;Port=5432;Database=AdMarketplace;Userna>
      - UNBUFFERED=1
      - DOTNET_LOGGING__CONSOLE__DISABLECOLORS=true
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
       - .env
    build:
      context: .
      dockerfile: AdMarketplace.WebApi/Dockerfile

  postgres:
    image: hub.hamdocker.ir/postgres:16-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=AdMarketplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: