// <auto-generated />
using System;
using AdMarketplace.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdMarketplace.Database.Migrations
{
    [DbContext(typeof(AdMarketDbContext))]
    [Migration("20260206152504_SwitchCampaignJsonToOwnedTypes")]
    partial class SwitchCampaignJsonToOwnedTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AdMarketplace")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdMarketplace.Database.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SessionPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("True");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Agents", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApplicationDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Brief")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<decimal>("BudgetTon")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaxPricePerPlacement")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Campaigns", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.CampaignApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<byte>("ProposedAdFormat")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("ProposedPostingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProposedPriceTon")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<byte>("ProposedPriceType")
                        .HasColumnType("smallint");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CampaignId", "ChannelId")
                        .IsUnique();

                    b.ToTable("CampaignApplications", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.CampaignInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<byte>("ProposedAdFormat")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("ProposedPostingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProposedPriceTon")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<byte>("ProposedPriceType")
                        .HasColumnType("smallint");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CampaignId", "ChannelId")
                        .IsUnique();

                    b.ToTable("CampaignInvitations", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("AverageViews")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PremiumCount")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("SubscriberCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Channels", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.ChannelPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte>("AdFormat")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriceTon")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<byte>("PriceType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelPricings", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualPostTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("AdFormat")
                        .HasColumnType("smallint");

                    b.Property<string>("AdvertiserFeedback")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountTon")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AutoCancelAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DraftMessageId")
                        .HasColumnType("bigint");

                    b.Property<byte>("DraftStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("EscrowWalletAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("FundsReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PostedMessageId")
                        .HasColumnType("bigint");

                    b.Property<byte>("PriceType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("ScheduledPostTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("AutoCancelAt");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Deals", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.UserChannelConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ChatId")
                        .IsUnique();

                    b.ToTable("UserChannelConnections", "AdMarketplace");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Campaign", b =>
                {
                    b.HasOne("AdMarketplace.Database.Models.User", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdMarketplace.Database.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("AdMarketplace.Domain.Contracts.Common.CampaignCreativeContract", "CreativeJson", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<bool>("RequiresApproval");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns", "AdMarketplace");

                            b1
                                .ToJson("CreativeJson")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");

                            b1.OwnsMany("AdMarketplace.Domain.Contracts.Common.CallToActionButton", "CallToActionButtons", b2 =>
                                {
                                    b2.Property<Guid>("CampaignCreativeContractCampaignId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(64);

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasMaxLength(512);

                                    b2.HasKey("CampaignCreativeContractCampaignId", "__synthesizedOrdinal");

                                    b2.ToTable("Campaigns", "AdMarketplace");

                                    b2.WithOwner()
                                        .HasForeignKey("CampaignCreativeContractCampaignId");
                                });

                            b1.Navigation("CallToActionButtons");
                        });

                    b.OwnsOne("AdMarketplace.Domain.Contracts.Common.CampaignTargetingContract", "TargetingJson", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<int?>("MaxSubscribers");

                            b1.Property<int?>("MinAverageViews");

                            b1.Property<int?>("MinPremiumPercentage");

                            b1.Property<int?>("MinSubscribers");

                            b1.PrimitiveCollection<string>("PreferredAdFormats");

                            b1.PrimitiveCollection<string>("PreferredCategoryIds");

                            b1.PrimitiveCollection<string>("PreferredLanguages");

                            b1.PrimitiveCollection<string>("PreferredPriceTypes");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns", "AdMarketplace");

                            b1
                                .ToJson("TargetingJson")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.Navigation("Advertiser");

                    b.Navigation("Category");

                    b.Navigation("CreativeJson");

                    b.Navigation("TargetingJson");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.CampaignApplication", b =>
                {
                    b.HasOne("AdMarketplace.Database.Models.Campaign", "Campaign")
                        .WithMany("Applications")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdMarketplace.Database.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.CampaignInvitation", b =>
                {
                    b.HasOne("AdMarketplace.Database.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdMarketplace.Database.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Channel", b =>
                {
                    b.HasOne("AdMarketplace.Database.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AdMarketplace.Database.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AdMarketplace.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("AdMarketplace.Domain.Contracts.Common.LanguageDistributionContract", "LanguageDistributionJson", b1 =>
                        {
                            b1.Property<Guid>("ChannelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16);

                            b1.Property<double>("Percentage");

                            b1.HasKey("ChannelId", "__synthesizedOrdinal");

                            b1.ToTable("Channels", "AdMarketplace");

                            b1
                                .ToJson("LanguageDistributionJson")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChannelId");
                        });

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("LanguageDistributionJson");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.ChannelPricing", b =>
                {
                    b.HasOne("AdMarketplace.Database.Models.Channel", "Channel")
                        .WithMany("Pricings")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Deal", b =>
                {
                    b.HasOne("AdMarketplace.Database.Models.User", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdMarketplace.Database.Models.CampaignApplication", "Application")
                        .WithOne("Deal")
                        .HasForeignKey("AdMarketplace.Database.Models.Deal", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdMarketplace.Database.Models.Campaign", "Campaign")
                        .WithMany("Deals")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdMarketplace.Database.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdMarketplace.Database.Models.CampaignInvitation", "Invitation")
                        .WithOne("Deal")
                        .HasForeignKey("AdMarketplace.Database.Models.Deal", "InvitationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Advertiser");

                    b.Navigation("Application");

                    b.Navigation("Campaign");

                    b.Navigation("Channel");

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.UserChannelConnection", b =>
                {
                    b.HasOne("AdMarketplace.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Campaign", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Deals");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.CampaignApplication", b =>
                {
                    b.Navigation("Deal");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.CampaignInvitation", b =>
                {
                    b.Navigation("Deal");
                });

            modelBuilder.Entity("AdMarketplace.Database.Models.Channel", b =>
                {
                    b.Navigation("Pricings");
                });
#pragma warning restore 612, 618
        }
    }
}
