<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AdMarketplace.Domain</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <UserSecretsId>5c1a4eae-4fbb-4e86-9cee-5abfcaa63526</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ErrorOr" Version="2.0.1" />
    </ItemGroup>

</Project>
