name: Deploy to Server

on:
  push:
    tags:
      - 'v*release*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd src/Back-End || git clone https://github.com/MahdiyarGHD/Ad-Marketplace-Contest.git /var/admarketplace && cd /var/admarketplace
            git pull origin Develop
            
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" > .env
            echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" > .env
            
            docker compose up -d --build
            docker image prune -f
