name: Deploy to Server

on:
  push:
    tags:
      - 'v*release*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            DEPLOY_DIR="/var/www/admarketplace"

            if [ ! -d "$DEPLOY_DIR" ]; then
              echo "Directory does not exist. Cloning repository..."
              git clone https://github.com/MahdiyarGHD/Ad-Marketplace-Contest.git "$DEPLOY_DIR"
            fi

            cd "$DEPLOY_DIR" || exit 1  # 'exit 1' stops the script if cd fails

            git fetch --all --tags
            git checkout ${{ github.ref_name }} 

            printf "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}\nWEBHOOK_URL=${{ secrets.WEBHOOK_URL }}\n" > .env

            docker compose down
            docker compose up -d --build
            docker image prune -f
